name = "want-extract"
main = "want-worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "WANT_KV"
id = "dcf2e413148f4543aab9a521aae37871"

# OAuth environment variables (to be set in Cloudflare dashboard)
# GOOGLE_CLIENT_ID = "your-google-client-id"
# GOOGLE_CLIENT_SECRET = "your-google-client-secret"
# APPLE_CLIENT_ID = "your-apple-services-id"
# APPLE_TEAM_ID = "your-apple-team-id"
# APPLE_KEY_ID = "your-apple-key-id"
# APPLE_PRIVATE_KEY = "your-apple-private-key"
# JWT_SECRET = "your-jwt-secret"
# ALLOWED_ORIGIN = "http://localhost:8054"
# REDIRECT_AFTER_LOGIN = "http://localhost:8054"

[env.production]
name = "want-extract"
route = "want.fiorearcangelodesign.workers.dev/*"

[env.staging]
name = "want-extract-staging"
